project_name: ass
before:
  hooks:
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    goos: # 编译平台列表 
      - linux
      - windows
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 7
    ldflags: 
      - "-s -w"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
checksum:
  name_template: 'checksums.txt'
archives:
  format: binary
  replacements:
    darwin: macos
  name_template: '{{ tolower .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ with .Arm }}v{{ . }}{{ end }}'  
release:
  tag: "{{ .CurrentTag }}"
  name_template: "{{.ProjectName}} - v{{.Version}}"
  mode: replace
changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
      - '^release:'
      - '^dep:'
      - 'typo'
    include:
      - "^feat:"