version: 2
project_name: ass
before:
  hooks:
    - go mod tidy
builds:
  - id: master
    env:
      - CGO_ENABLED=0
    goos: # 编译平台列表 
      - linux
      - windows
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 7
    ldflags: 
      - "-s -w"
    ignore:
      - goarch: arm64
        goos: windows
      - goarch: arm
        goos: windows
checksum:
  name_template: 'checksums.txt'
archives:
  - id: binary
    format: binary
    name_template: >-
      {{- tolower .ProjectName }}-v
      {{- .Version }}-
      {{- replace .Os "darwin" "macos" }}-
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}  
release:
  name_template: "AlistAutoStrm - v{{.Version}}"
  mode: keep-existing
  prerelease: auto
changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - '^test:'
      - '^dep:'
      - 'typo'
    include:
      - "^feat:"